### ISSUE TITLE
Github workflow fails for a link that results in 404

### ISSUE THREAD

**Issue by BOLT04** [ErikCH/DevYouTubeList#108]
Hi everyone 👋,

I noticed the GitHub Workflow for checking the markdown links is failing with [this link](https://youtube.com/c/codyseibert), since it results on a 404 response. Is the correct link for this channel [this one](https://www.youtube.com/channel/UCsrVDPJBYeXItETFHG0qzyw/featured)?

I double-checked and saw @codyseibert added it to the **Up and Coming** section, so I just wanted to make sure if the link is correct.

Would love your feedback 🙂,
Thanks.

**Comment by ErikCH** [comment]
@BOLT04 Thanks I see that! I went ahead and removed it. Let's see if the link checker works now. thanks!
