### ISSUE TITLE
Add channel "Context Free"?

### ISSUE THREAD

**Issue by tjpalmer** [ErikCH/DevYouTubeList#38]
Hi! I was wondering if you take requests for additions.

I started a channel a couple of months ago called [Context Free](https://www.youtube.com/channel/UCS4FAVeYW_IaZqAbqhlvxlA), currently with just 125 subscribers.

I focus primarily on programming languages, including design, history, and coding sessions to demo features in and across languages. My goal is to be useful to both new and experienced programmers (including programming language designers).

**Comment by rubayet170746** [comment]
you can create a pull request then the moderator will consider that ....

**Comment by ErikCH** [comment]
@tjpalmer Hi! Create a pull request and get it added in! Make sure to add it in the Up and coming section!
