### ISSUE TITLE
Request for clasification

### ISSUE THREAD

**Issue by sukhchainn** [ErikCH/DevYouTubeList#67]
Mega Meter, fully loaded mega meter of Dev YouTubers.

* First, I'm glad that you made this list of Dev YouTubers, I was looking for one for a very long time.
There is one problem; this list doesn't tell me which technologies these YouTube channels specialize in. 
* Second, I would like to list some channels here that I couldn't find in your list, with their specialization :-
    
1. - The Cherno ; C++/Visual Studio
2. - javidx9 ; C++/Visual Studio
3. - Engineer Man ; C/Rust/Python/JavaScript/Unity
4. - Two Minute Papers ; PHD Papers 
5. - The Audio Programmer ; C++/JUCE
6. - Jake Wright ; competitive Programming
7. - Coder's Tape ; PHP
8. - techsith ; JavaScript
9. - Programming with Peter ; PHP
10. - Seytonic ; (Informational)
11. - JAMstack Conf ; Tech Conference
12. - Rachit Jain ; competitive Programming
13. - CHM Tech ; (Informational)
14. - CrashCourse ; AI
15. - The Ape Machine ; AI
16. - Barry Brown ; Python/Java/SQL/C
17. - CppNuts ; C++/Advance C++
18. - Coding Walnut ; C (Up And Coming)

I hope you will add these to your Mega Meter.
:+1:

**Comment by ErikCH** [comment]
Thanks Mega Meter! For the first part yes! I would love to have more categories that break down each tutorial channel by the main technology they use, or at least a more specific category then just "tutorial".  Issue #1 covers that. 

As for these other channels, can your, or someone push a PR for them so we can get them added.

**Comment by sukhchainn** [comment]
I will push a PR with embedded links, I will mention categories in double quotes so that they will be easily categorized later when someone starts working on 'Add more categories' issue.

**Comment by sukhchainn** [comment]
@ErikCH, I made a pull request. I hope that you will make me an assignee of this issue before closing it for the sake of thread history.

**Comment by sukhchainn** [comment]
There were too many conflicts and there are other pull requests in line so I'm putting these channel names right here, whoever is in-charge of categorization can add these to the list.

==========

# This list is subject to change so these will be adjusted accordingly

### "Web Development"
    
* [Coder's Tape](https://www.youtube.com/channel/UCQI-Ym2rLZx52vEoqlPQMdg) : PHP
* [techsith](https://www.youtube.com/user/techSithTube) : JavaScript
* [Programming with Peter](https://www.youtube.com/channel/UCqqQLR77gh9nB-HExBYVIoQ) : PHP
    
### "Machine Learning"

* [CrashCourse](https://www.youtube.com/user/crashcourse) : AI
* [The Ape Machine](https://www.youtube.com/channel/UCLQC-Ocea1wFl3PgsSIPR0g) : AI

### "C/C++ Development"

* [The Cherno](https://www.youtube.com/user/TheChernoProject) : C++/Visual Studio
* [javidx9](https://www.youtube.com/channel/UC-yuWVUplUJZvieEligKBkA) : C++/Visual Studio
* [Engineer Man](https://www.youtube.com/channel/UCrUL8K81R4VBzm-KOYwrcxQ) : C/Rust/Python/JavaScript/Unity
* [The Audio Programmer](https://www.youtube.com/channel/UCpKb02FsH4WH4X_2xhIoJ1A) : C++/JUCE
* [Barry Brown](https://www.youtube.com/user/profbbrown) : Python/Java/SQL/C
* [CppNuts](https://www.youtube.com/user/MrRupeshyadav/playlists) : C++/Advance C++
* [Coding Walnut](https://www.youtube.com/channel/UCcPJIQLMIpOqZv0wt-FFQsw) : C (Up And Coming)

### "Interview Preperation"

* [Rachit Jain](https://www.youtube.com/channel/UC9fDC_eBh9e_bogw87DbGKQ) : competitive Programming
* [Jake Wright](https://www.youtube.com/user/jaketvee) : competitive Programming

### "Informative"
    
* [Seytonic](https://www.youtube.com/channel/UCW6xlqxSY3gGur4PkGPEUeA) : Security
* [JAMstack Conf](https://www.youtube.com/channel/UC8bRyfU7ycLXnEBfvdorpUg) : Tech Conference
* [CHM Tech](https://www.youtube.com/user/hotmonkey000) : Miscellaneous
* [Two Minute Papers](https://www.youtube.com/user/keeroyz) : PHD Papers
