### ISSUE TITLE
Sort by Name

### ISSUE THREAD

**Issue by claudiobernasconi** [ErikCH/DevYouTubeList#85]
It might be useful to sort the channels by name (within a category). I believe the current order is random and does not offer any benefit to alphabetical order.

What are your opinions on this? I'd create a PR if that is what you'd like to have.

**Comment by sukhchainn** [comment]
I'm currently working on refactoring the entire list. I will create a grep command to order the list alphabetically or it can be done in JavaScript too. Please tell me which one you are comfortable in.

**Comment by claudiobernasconi** [comment]
You're basically talking about an automated solution to the issue I pointed out? I'm okay with however this gets done, but I believe it should be done. I'm sure the owner of the repo would be okay with you making a script to do that.

**Comment by sukhchainn** [comment]
@claudiobernasconi Automation script is still far but I have sorted the list manually now and the pull request which contains the changes is #69

**Comment by ErikCH** [comment]
I like the idea of automating this somewhow so the list is alphabetical. With that said, I'm not sure exactly how this would work. Unless it was some sort of action that could be run on each PR... I don't know... The problem is, that new contributors are NOT going to be able to put every new channel in alphabetically into the list... and I don't want to have to do it manually for each new PR.

**Comment by sukhchainn** [comment]
@ErikCH you don't have to worry about it. The script is mostly non-interactive which means you don't have to interact with it to get the basic tasks done. The contributor would just need to create a "new.md" file and in that file write all the new entries under the correct heading. The script will match the corresponding heading and add the new entries in that section.

I can understand your concerns, but you don't have to worry about anything. I am following UGU(User Group Universality) principals here which are considered best practices for CLI tools.

**Comment by anuraghazra** [comment]
We can run sorting script in each PR with Github Actions and update the contents of the readme.md file automatically.

**Comment by ErikCH** [comment]
@anuraghazra @sukhchainn Where is this script now?

**Comment by jspw** [comment]
hey @ErikCH ,  i have sorted the youtube channel lists in alphabetical order .You can check my pull request .
